//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagementProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryTable
    {
        public int SalaryId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<decimal> GrossSalary { get; set; }
        public Nullable<decimal> BasicSalary { get; set; }
        public Nullable<decimal> HouseRentAllowance { get; set; }
        public Nullable<decimal> DearnessAllowance { get; set; }
        public Nullable<decimal> ConveyanceAllowance { get; set; }
        public Nullable<decimal> MedicalAllowance { get; set; }
        public Nullable<decimal> OtherAllowance { get; set; }
        public Nullable<decimal> ProvidentFund { get; set; }
        public Nullable<decimal> ESI { get; set; }
        public Nullable<decimal> ProfessionalTax { get; set; }
        public Nullable<decimal> NetSalary { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
    }
}
